/* Generated by Yosys 0.16+6 (git sha1 7f5477eb1, gcc 9.1.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "bram_sdp.v:44.1-74.10" *)
module BRAM_SDP_32x512(clk, rce, ra, rq, wce, wa, wd);
  (* unused_bits = "32 33 34 35" *)
  wire [35:0] _0_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:318.14-318.19" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35" *)
  wire [35:0] _1_;
  (* src = "bram_sdp.v:57.12-57.15" *)
  input clk;
  wire clk;
  (* src = "bram_sdp.v:59.26-59.28" *)
  input [8:0] ra;
  wire [8:0] ra;
  (* src = "bram_sdp.v:58.26-58.29" *)
  input rce;
  wire rce;
  (* src = "bram_sdp.v:60.26-60.28" *)
  output [31:0] rq;
  wire [31:0] rq;
  (* src = "bram_sdp.v:62.26-62.28" *)
  input [8:0] wa;
  wire [8:0] wa;
  (* src = "bram_sdp.v:61.26-61.29" *)
  input wce;
  wire wce;
  (* src = "bram_sdp.v:63.26-63.28" *)
  input [31:0] wd;
  wire [31:0] wd;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:408.9-442.3" *)
  TDP36K #(
    .MODE_BITS(81'h00140281b6c0140140db6)
  ) \BRAM_32x512.memory.0.0.0  (
    .ADDR_A1_i({ 1'h0, ra, 5'h00 }),
    .ADDR_A2_i({ ra, 5'h00 }),
    .ADDR_B1_i({ 1'h0, wa, 5'h00 }),
    .ADDR_B2_i({ wa, 5'h00 }),
    .BE_A1_i({ rce, rce }),
    .BE_A2_i({ rce, rce }),
    .BE_B1_i({ wce, wce }),
    .BE_B2_i({ wce, wce }),
    .CLK_A1_i(clk),
    .CLK_A2_i(clk),
    .CLK_B1_i(clk),
    .CLK_B2_i(clk),
    .FLUSH1_i(1'h0),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(rq[17:0]),
    .RDATA_A2_o({ _0_[35:32], rq[31:18] }),
    .RDATA_B1_o(_1_[17:0]),
    .RDATA_B2_o(_1_[35:18]),
    .REN_A1_i(rce),
    .REN_A2_i(rce),
    .REN_B1_i(1'h0),
    .REN_B2_i(1'h0),
    .RESET_ni(1'h1),
    .WDATA_A1_i(18'h3ffff),
    .WDATA_A2_i(18'h3ffff),
    .WDATA_B1_i(wd[17:0]),
    .WDATA_B2_i({ 4'hx, wd[31:18] }),
    .WEN_A1_i(1'h0),
    .WEN_A2_i(1'h0),
    .WEN_B1_i(wce),
    .WEN_B2_i(wce)
  );
  assign _0_[31:0] = rq;
endmodule
