/* Generated by Yosys 0.16+6 (git sha1 7f5477eb1, gcc 9.1.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "bram_tdp.v:227.1-279.10" *)
module BRAM_TDP_4x4096(clk_a, rce_a, ra_a, rq_a, wce_a, wa_a, wd_a, clk_b, rce_b, ra_b, rq_b, wce_b, wa_b, wd_b);
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _00_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _01_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _02_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _03_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _04_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _05_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _06_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _07_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _08_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _09_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _10_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:83.25-83.90" *)
  wire _11_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _12_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _13_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _14_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _15_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _16_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _17_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _18_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _19_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _20_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _21_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _22_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:84.25-84.90" *)
  wire _23_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:54.22-54.33" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [35:4] _24_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:55.22-55.33" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [35:4] _25_;
  (* src = "bram_tdp.v:248.10-248.15" *)
  input clk_a;
  wire clk_a;
  (* src = "bram_tdp.v:256.10-256.15" *)
  input clk_b;
  wire clk_b;
  (* src = "bram_tdp.v:250.26-250.30" *)
  input [11:0] ra_a;
  wire [11:0] ra_a;
  (* src = "bram_tdp.v:258.26-258.30" *)
  input [11:0] ra_b;
  wire [11:0] ra_b;
  (* src = "bram_tdp.v:249.26-249.31" *)
  input rce_a;
  wire rce_a;
  (* src = "bram_tdp.v:257.26-257.31" *)
  input rce_b;
  wire rce_b;
  (* src = "bram_tdp.v:251.26-251.30" *)
  output [3:0] rq_a;
  wire [3:0] rq_a;
  (* src = "bram_tdp.v:259.26-259.30" *)
  output [3:0] rq_b;
  wire [3:0] rq_b;
  (* src = "bram_tdp.v:253.26-253.30" *)
  input [11:0] wa_a;
  wire [11:0] wa_a;
  (* src = "bram_tdp.v:261.26-261.30" *)
  input [11:0] wa_b;
  wire [11:0] wa_b;
  (* src = "bram_tdp.v:252.26-252.31" *)
  input wce_a;
  wire wce_a;
  (* src = "bram_tdp.v:260.26-260.31" *)
  input wce_b;
  wire wce_b;
  (* src = "bram_tdp.v:254.26-254.30" *)
  input [3:0] wd_a;
  wire [3:0] wd_a;
  (* src = "bram_tdp.v:262.26-262.30" *)
  input [3:0] wd_b;
  wire [3:0] wd_b;
  assign _23_ = 16'hf088 >> { rce_a, ra_a[7], wa_a[7], wce_a };
  assign _17_ = 16'hf088 >> { rce_a, ra_a[1], wa_a[1], wce_a };
  assign _16_ = 16'hf088 >> { rce_a, ra_a[0], wa_a[0], wce_a };
  assign _20_ = 16'hf088 >> { rce_a, ra_a[4], wa_a[4], wce_a };
  assign _12_ = 16'hf088 >> { rce_a, ra_a[8], wa_a[8], wce_a };
  assign _13_ = 16'hf088 >> { rce_a, ra_a[9], wa_a[9], wce_a };
  assign _07_ = 16'hf088 >> { rce_b, ra_b[3], wa_b[3], wce_b };
  assign _14_ = 16'hf088 >> { rce_a, ra_a[10], wa_a[10], wce_a };
  assign _04_ = 16'hf088 >> { rce_b, ra_b[0], wa_b[0], wce_b };
  assign _15_ = 16'hf088 >> { rce_a, ra_a[11], wa_a[11], wce_a };
  assign _18_ = 16'hf088 >> { rce_a, ra_a[2], wa_a[2], wce_a };
  assign _19_ = 16'hf088 >> { rce_a, ra_a[3], wa_a[3], wce_a };
  assign _22_ = 16'hf088 >> { rce_a, ra_a[6], wa_a[6], wce_a };
  assign _21_ = 16'hf088 >> { rce_a, ra_a[5], wa_a[5], wce_a };
  assign _06_ = 16'hf088 >> { rce_b, ra_b[2], wa_b[2], wce_b };
  assign _03_ = 16'hf088 >> { rce_b, ra_b[11], wa_b[11], wce_b };
  assign _02_ = 16'hf088 >> { rce_b, ra_b[10], wa_b[10], wce_b };
  assign _01_ = 16'hf088 >> { rce_b, ra_b[9], wa_b[9], wce_b };
  assign _00_ = 16'hf088 >> { rce_b, ra_b[8], wa_b[8], wce_b };
  assign _11_ = 16'hf088 >> { rce_b, ra_b[7], wa_b[7], wce_b };
  assign _10_ = 16'hf088 >> { rce_b, ra_b[6], wa_b[6], wce_b };
  assign _09_ = 16'hf088 >> { rce_b, ra_b[5], wa_b[5], wce_b };
  assign _08_ = 16'hf088 >> { rce_b, ra_b[4], wa_b[4], wce_b };
  assign _05_ = 16'hf088 >> { rce_b, ra_b[1], wa_b[1], wce_b };
  (* module_not_derived = 32'd1 *)
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:132.9-166.3" *)
  TDP36K #(
    .MODE_BITS(81'h001402824900140141248)
  ) \BRAM_TDP_4x4096.memory.0.0.0  (
    .ADDR_A1_i({ 1'h0, _03_, _02_, _01_, _00_, _11_, _10_, _09_, _08_, _07_, _06_, _05_, _04_, 2'h0 }),
    .ADDR_A2_i({ _03_, _02_, _01_, _00_, _11_, _10_, _09_, _08_, _07_, _06_, _05_, _04_, 2'h0 }),
    .ADDR_B1_i({ 1'h0, _15_, _14_, _13_, _12_, _23_, _22_, _21_, _20_, _19_, _18_, _17_, _16_, 2'h0 }),
    .ADDR_B2_i({ _15_, _14_, _13_, _12_, _23_, _22_, _21_, _20_, _19_, _18_, _17_, _16_, 2'h0 }),
    .BE_A1_i({ 1'hx, wce_b }),
    .BE_A2_i(2'hx),
    .BE_B1_i({ 1'hx, wce_a }),
    .BE_B2_i(2'hx),
    .CLK_A1_i(clk_b),
    .CLK_A2_i(clk_b),
    .CLK_B1_i(clk_a),
    .CLK_B2_i(clk_a),
    .FLUSH1_i(1'h0),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o({ _24_[17:4], rq_b }),
    .RDATA_A2_o(_24_[35:18]),
    .RDATA_B1_o({ _25_[17:4], rq_a }),
    .RDATA_B2_o(_25_[35:18]),
    .REN_A1_i(rce_b),
    .REN_A2_i(rce_b),
    .REN_B1_i(rce_a),
    .REN_B2_i(rce_a),
    .RESET_ni(1'h1),
    .WDATA_A1_i({ 14'hxxxx, wd_b }),
    .WDATA_A2_i(18'hxxxxx),
    .WDATA_B1_i({ 14'hxxxx, wd_a }),
    .WDATA_B2_i(18'hxxxxx),
    .WEN_A1_i(wce_b),
    .WEN_A2_i(wce_b),
    .WEN_B1_i(wce_a),
    .WEN_B2_i(wce_a)
  );
endmodule
