/* Generated by Yosys 0.16+6 (git sha1 7f5477eb1, gcc 9.1.0 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "bram_tdp.v:66.1-118.10" *)
module BRAM_TDP_32x512(clk_a, rce_a, ra_a, rq_a, wce_a, wa_a, wd_a, clk_b, rce_b, ra_b, rq_b, wce_b, wa_b, wd_b);
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _00_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _01_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _02_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _03_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _04_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _05_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _06_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _07_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:110.25-110.90" *)
  wire _08_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _09_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _10_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _11_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _12_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _13_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _14_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _15_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _16_;
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:111.25-111.90" *)
  wire _17_;
  (* unused_bits = "32 33 34 35" *)
  wire [35:0] _18_;
  (* unused_bits = "32 33 34 35" *)
  wire [35:0] _19_;
  (* src = "bram_tdp.v:87.10-87.15" *)
  input clk_a;
  wire clk_a;
  (* src = "bram_tdp.v:94.10-94.15" *)
  input clk_b;
  wire clk_b;
  (* src = "bram_tdp.v:89.26-89.30" *)
  input [8:0] ra_a;
  wire [8:0] ra_a;
  (* src = "bram_tdp.v:96.26-96.30" *)
  input [8:0] ra_b;
  wire [8:0] ra_b;
  (* src = "bram_tdp.v:88.26-88.31" *)
  input rce_a;
  wire rce_a;
  (* src = "bram_tdp.v:95.26-95.31" *)
  input rce_b;
  wire rce_b;
  (* src = "bram_tdp.v:90.26-90.30" *)
  output [31:0] rq_a;
  wire [31:0] rq_a;
  (* src = "bram_tdp.v:97.26-97.30" *)
  output [31:0] rq_b;
  wire [31:0] rq_b;
  (* src = "bram_tdp.v:92.26-92.30" *)
  input [8:0] wa_a;
  wire [8:0] wa_a;
  (* src = "bram_tdp.v:99.26-99.30" *)
  input [8:0] wa_b;
  wire [8:0] wa_b;
  (* src = "bram_tdp.v:91.26-91.31" *)
  input wce_a;
  wire wce_a;
  (* src = "bram_tdp.v:98.26-98.31" *)
  input wce_b;
  wire wce_b;
  (* src = "bram_tdp.v:93.26-93.30" *)
  input [31:0] wd_a;
  wire [31:0] wd_a;
  (* src = "bram_tdp.v:100.26-100.30" *)
  input [31:0] wd_b;
  wire [31:0] wd_b;
  assign _13_ = 16'hf088 >> { rce_a, ra_a[0], wa_a[0], wce_a };
  assign _14_ = 16'hf088 >> { rce_a, ra_a[1], wa_a[1], wce_a };
  assign _15_ = 16'hf088 >> { rce_a, ra_a[2], wa_a[2], wce_a };
  assign _16_ = 16'hf088 >> { rce_a, ra_a[3], wa_a[3], wce_a };
  assign _17_ = 16'hf088 >> { rce_a, ra_a[4], wa_a[4], wce_a };
  assign _09_ = 16'hf088 >> { rce_a, ra_a[5], wa_a[5], wce_a };
  assign _10_ = 16'hf088 >> { rce_a, ra_a[6], wa_a[6], wce_a };
  assign _11_ = 16'hf088 >> { rce_a, ra_a[7], wa_a[7], wce_a };
  assign _12_ = 16'hf088 >> { rce_a, ra_a[8], wa_a[8], wce_a };
  assign _04_ = 16'hf088 >> { rce_b, ra_b[0], wa_b[0], wce_b };
  assign _05_ = 16'hf088 >> { rce_b, ra_b[1], wa_b[1], wce_b };
  assign _06_ = 16'hf088 >> { rce_b, ra_b[2], wa_b[2], wce_b };
  assign _07_ = 16'hf088 >> { rce_b, ra_b[3], wa_b[3], wce_b };
  assign _08_ = 16'hf088 >> { rce_b, ra_b[4], wa_b[4], wce_b };
  assign _00_ = 16'hf088 >> { rce_b, ra_b[5], wa_b[5], wce_b };
  assign _01_ = 16'hf088 >> { rce_b, ra_b[6], wa_b[6], wce_b };
  assign _02_ = 16'hf088 >> { rce_b, ra_b[7], wa_b[7], wce_b };
  assign _03_ = 16'hf088 >> { rce_b, ra_b[8], wa_b[8], wce_b };
  (* module_not_derived = 32'd1 *)
  (* src = "/home/users/lilit.hunanyan/workspace/bram/yosys_verific_rs/yosys/install/bin/../share/yosys/rapidsilicon/genesis/brams_map.v:132.9-166.3" *)
  TDP36K #(
    .MODE_BITS(81'h00140281b6c0140140db6)
  ) \BRAM_TDP_32x512.memory.0.0.0  (
    .ADDR_A1_i({ 1'h0, _03_, _02_, _01_, _00_, _08_, _07_, _06_, _05_, _04_, 5'h00 }),
    .ADDR_A2_i({ _03_, _02_, _01_, _00_, _08_, _07_, _06_, _05_, _04_, 5'h00 }),
    .ADDR_B1_i({ 1'h0, _12_, _11_, _10_, _09_, _17_, _16_, _15_, _14_, _13_, 5'h00 }),
    .ADDR_B2_i({ _12_, _11_, _10_, _09_, _17_, _16_, _15_, _14_, _13_, 5'h00 }),
    .BE_A1_i({ wce_b, wce_b }),
    .BE_A2_i({ wce_b, wce_b }),
    .BE_B1_i({ wce_a, wce_a }),
    .BE_B2_i({ wce_a, wce_a }),
    .CLK_A1_i(clk_b),
    .CLK_A2_i(clk_b),
    .CLK_B1_i(clk_a),
    .CLK_B2_i(clk_a),
    .FLUSH1_i(1'h0),
    .FLUSH2_i(1'h0),
    .RDATA_A1_o(rq_b[17:0]),
    .RDATA_A2_o({ _18_[35:32], rq_b[31:18] }),
    .RDATA_B1_o(rq_a[17:0]),
    .RDATA_B2_o({ _19_[35:32], rq_a[31:18] }),
    .REN_A1_i(rce_b),
    .REN_A2_i(rce_b),
    .REN_B1_i(rce_a),
    .REN_B2_i(rce_a),
    .RESET_ni(1'h1),
    .WDATA_A1_i(wd_b[17:0]),
    .WDATA_A2_i({ 4'hx, wd_b[31:18] }),
    .WDATA_B1_i(wd_a[17:0]),
    .WDATA_B2_i({ 4'hx, wd_a[31:18] }),
    .WEN_A1_i(wce_b),
    .WEN_A2_i(wce_b),
    .WEN_B1_i(wce_a),
    .WEN_B2_i(wce_a)
  );
  assign _18_[31:0] = rq_b;
  assign _19_[31:0] = rq_a;
endmodule
