name: CI regression tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
      runs-on: yosys_rs_plugin_builder
      steps:
        - name: Cancel previous
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}

        - name: Runner workspace path
          run: |
            echo "Cleaning up previous run"
            rm -rf "${{ github.workspace }}"
            mkdir -p "${{ github.workspace }}"

        - name: Checkout yosys_verific_rs
          run: |
            git clone git@github.com:RapidSilicon/yosys_verific_rs.git
            cd yosys_verific_rs
            git submodule update --init --recursive

        - name: Build yosys_verific_rs
          run: |
            cd yosys_verific_rs
            make build_yosys_verific

        - name: Run tests
          run: |
            cd yosys_verific_rs/yosys-rs-plugin
            make test YOSYS_PATH=$(realpath ../yosys/install)
