name: Increment Version

on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Increment patch version
      run: |
        SYNTH_CC_FILE=$(realpath src)/synth_rapidsilicon.cc
        CURR_VERSION=$(grep "VERSION_PATCH" $SYNTH_CC_FILE | grep -Eo '[0-9]*')
        let "NEW_VERSION=CURR_VERSION+1"
        sed -i "s/VERSION_PATCH $CURR_VERSION/VERSION_PATCH $NEW_VERSION/g" $SYNTH_CC_FILE
        

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Incremented patch version'
        committer_name: GitHub Actions
        add: 'src/synth_rapidsilicon.cc'
